# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fa9257250ff64ad1771609d112e4aad90c07f1edab21694cfb2c3ab90494e4ef0743dbb41956c720d6d92fe84b3abd150b6bd5dc689d8f9ad744949b15a8766

test:
  secret_key_base: 0283c0dee7a92f5a6aa7aaf88a29d8ef26d4deef4ae248d0b954bcb74eb28182f9611d5dc1b8ed0dcf096efb11b20d857b8e0d0cada593486c8b95382c5e1a27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
